#!/usr/bin/env bash

# exit when any command fails
set -e

if [ ${HOME} == '/home/pingraham' ]; then
  echo 'Variable is set'
#  exit
fi

# The packages will be cloned and installed in the following folder
# It is strongly recommened NOT to modify this
REPOS=$HOME"/auto-op-env-packages/"

# Check if the directory exists
if [ -d $REPOS ]; then
  printf "Directory "$REPOS" exists. Remove directory and contents and re-run. \n"
  exit
fi
## Start cloning and setting up packages
printf "Repositories will cloned and setup in the directory: $REPOS \n"
mkdir ${REPOS}

# Check if folders are already present before installing
printf 'Setting up lsst-dm/Spectractor \n'
if [ -d $REPOS"/Spectractor" ]
then
    printf "Directory "$REPOS"/Spectractor exists. Skipping package install and leaving original.\n"
else
    cd $REPOS
    printf "HERE! \n"
#    git clone https://github.com/lsst-dm/Spectractor.git
#    cd Spectractor
#    git checkout tickets/DM-28773
#    git reset origin/tickets/DM-28773 --hard
#    git pull
#    pip install -r requirements.txt
#    pip install -e .
fi
#
#
# Create file that will be *sourced* at the beginning of .user_setups
FILE_PATH=$REPOS"auto_env_setup.sh"
if [ -d $FILE_PATH ]; then
  printf "auto_env_setup.sh file already exists in "$REPOS". Removing. \n"
  rm -f $FILE_PATH
fi

printf "Creating a new auto_env_setup.sh in: ${REPOS} \n"

cat <<EOT >> $FILE_PATH
#!/usr/bin/env bash
# This file is auto generated by the package_setup_obsrun scripts.
# It is sourced by the ~/notebooks/.user_setups file
# Do not modify!
EOT

printf "setup -j rapid_analysis -r "$REPOS"rapid_analysis \n" >> $FILE_PATH
printf "setup -j atmospec -r "$REPOS"atmospec \n" >> $FILE_PATH
printf "setup -j cwfs -r "$REPOS"cwfs \n" >> $FILE_PATH


#check that ~/notebooks/.user_setups exists
USER_SETUP_PATH=$HOME"/notebooks/.user_setups"
if [ -a $USER_SETUP_PATH ] && [ -w $USER_SETUP_PATH ]; then
  # grab line3 of .user_setups for comparison
  LINE3_OF_EXISTING_FILE=$(sed '3 p' $USER_SETUP_PATH)
  # declare what we need it to say
  LINE3="source ${FILE_PATH}"
  # Check if content is already in .user_setups
  # FIXME - WHY AREN"T THESE EXACT? WHITESPACE? Wildcards should not be necessary
  if [[ $LINE3_OF_EXISTING_FILE != *"${LINE3}"* ]]; then
    printf "Adding source command to auto_env_setup.sh at the top of your ~/notebooks/.user_setups file \n"
    sed -i "1i$LINE3 \n" $USER_SETUP_PATH
    sed -i "1i# The first three lines of this file are added automatically by package_setup_obsrun script in $REPOS \n# DO NOT MODIFY OR MOVE" $USER_SETUP_PATH
  else
    printf "Source command already at the top of your ~/notebooks/.user_setups file. Skipping.\n"
  fi
else
  printf "No writable .user_setups found in ${USER_SETUP_PATH} \n"
  printf "Are you sure you're running this on a Nublado instance? \n"
  printf "Make sure file exists then re-run this script \n"
  exit
fi


printf "\nPackage setup script completed successfully\n"
printf "####################################################################################\n"
printf "WARNING: RESTART ALL NOTEBOOK KERNELS \n"
printf "WARNING: Verify no packages are being overwritten (setup) in your .user_setups file. \n"
printf "#################################################################################### \n"
